# Generated by Django 3.2.13 on 2022-12-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('MOV', 'type_movie'), ('TVS', 'tv_Show'), ('SER', 'serials')], default='MOV', max_length=150, verbose_name='type'),
        ),
    ]
