# Generated by Django 3.2.13 on 2022-12-22 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='row_created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='row_modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full_name')),
            ],
            options={
                'verbose_name': 'directors_verbose_name',
                'verbose_name_plural': 'directors_verbose_n_pl',
                'db_table': 'content"."directors',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='row_created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='row_modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full_name')),
            ],
            options={
                'verbose_name': 'writers_verbose_name',
                'verbose_name_plural': 'writers_verbose_n_pl',
                'db_table': 'content"."writers',
            },
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(max_length=150, null=True, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='WriterFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='row_created')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.writer', verbose_name='writer_verbose_name')),
            ],
            options={
                'verbose_name': 'writer_verbose_name',
                'verbose_name_plural': 'writer_verbose_n_pl',
                'db_table': 'content"."writer_film_work',
            },
        ),
        migrations.CreateModel(
            name='DirectorFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='row_created')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.director', verbose_name='director_verbose_name')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
            ],
            options={
                'verbose_name': 'director_verbose_name',
                'verbose_name_plural': 'director_verbose_n_pl',
                'db_table': 'content"."director_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='directors',
            field=models.ManyToManyField(through='movies.DirectorFilmwork', to='movies.Director'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='writers',
            field=models.ManyToManyField(through='movies.WriterFilmwork', to='movies.Writer'),
        ),
        migrations.AddConstraint(
            model_name='writerfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'writer'), name='film_work_writer_idx'),
        ),
        migrations.AddConstraint(
            model_name='directorfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'director'), name='film_work_director_idx'),
        ),
    ]
