# Generated by Django 3.2.13 on 2023-01-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20230104_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='movies.person', verbose_name='person_verbose_name'),
        ),
    ]
